version: "3"
services: 
  backend:
    build:
      dockerfile: Dockerfile.frontend
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      - database
    environment:
      - TYPE=mariadb
      - HOST=database
      - PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=classroom
      - OAUTH2_CLIENT_ID=20240304211915MyyeqIFFJ2Vz
      - OAUTH2_CLIENT_SECRET=t7rbVm2gc0sRzk3LTy4frJtLojd2pJV04kBgtz7K5MParhdjMnMjuQkC
      - OAUTH2_REDIRECT_URL=http://backend:3001/api/auth/authorize
      - SESSION_SECRET=123
  frontend:
    build: 
      dockerfile: Dockerfile.frontend
    restart: always
    ports: 
      - 3001:3001
    depends_on:
      - backend
    environment:
      - NITRO_PORT=3001
      - NUXT_PUBLIC_API_BASE=http://bankend:3001/api
  database:
    image: mariadb:11.2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - csie_classrom_dbdata:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=classroom
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootPassword
      - TZ=Asia/Taipei
volumes:
  csie_classrom_dbdata:

  
