export enum CurrencyTypes {
  TWD = "TWD",
  USD = "USD",
  EUR = "EUR",
  JPY = "JPY",
  KRW = "KRW",
  AUD = "AUD",
  CAD = "CAD",
  CNY = "CNY",
  GBP = "GBP",
  ZAR = "ZAR",
  SGD = "SGD",
  MXN = "MXN",
  THB = "THB",
  PHP = "PHP",
  VND = "VND",
  NZD = "NZD",
  CHF = "CHF",
  SEK = "SEK",
}
