apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}-database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ .Release.Name }}-database
  clusterIP: None


