frontend:
  replicas: 1
  image:
    repository: harbor.lan/finance-manager/frontend
    tag: v1.3.4
  envFromConfigMap: "frontend-env-config"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

backend:
  replicas: 1
  image:
    repository: harbor.lan/finance-manager/backend
    tag: v1.3.2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  envFromConfigMap: 
    - name: "backend-env-config"
    - name: "database-env-config"
  envFromSecret: 
    - name: "backend-env-secret"
    - name: "database-env-secret"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  hosts:
    - host: financemanager.local
      paths:
        - path: /api
          pathType: Prefix
          backend:
            serviceName: finance-manager-backend
            servicePort: 3000
        - path: /
          pathType: Prefix
          backend:
            serviceName: finance-manager-frontend
            servicePort: 80
  tls: []

database:
  image:
    repository: mariadb
    tag: 11.6-noble
  claimName: ""
  persistentVolumeClaim:
    className: "standard"
    name: "database"
    size: "1Gi"
  envFromConfigMap: "database-env-config"
  envFromSecret: "database-env-secret"

redis: 
  image:
    repository: redis
    tag: 7.4.2-bookworm